# TOPIC : LIST

states_of_america = ["Delaware", "Pensylvania"]



# WE CAN ALSO CHANGE THE SPELLING OF LIST ITEM BY THEIR INDEX
states_of_america[1] = "Pencilvania"
print(states_of_america)



# ADD SINGLE ITEM AT A TIME
states_of_america.append("Angelaland")
print(states_of_america)



# ADD MULTIPLE ITEM AT A TIME
states_of_america.extend(["Angelaland", "Soaeb", "Asif"])
print(states_of_america)


