# TITLE : INDEX ERROR AND WORKING WITH NESTED LIST.

states_of_america = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii","Idaho",  "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

num_of_states = len(states_of_america)

print(states_of_america[num_of_states - 1])




fruits = [
    "Strawberries",
    "Peaches",
    "Pears",
    "Nectarines",
    "Apples",
    "Grapes",
    "Cherries",
    "Blueberries"
]

vegetables = [
    "Spinach",
    "Kale, Collard, and Mustard Greens",
    "Bell Peppers and Hot Peppers",
    "Green Beans"
]

dirty_dozen = [fruits, vegetables]

print(dirty_dozen)


