# TOPIC : INDENTATION (don't try to run these code, these are only for understand indentation)

# e.g, 01)
'''
def mu_function():
....print('Hello')
print('World')

'''

# e.g, 02)

'''
def mu_function():
....print('Hello')
    print('World')
    
'''


# e.g, 03)

'''
def my_function():
    if sky == "clear":
        print("Blue")
    elif sky == "cloudy":
        print("Grey")
    print("Hello")
print("World")

'''