# Project: Higher Lower game

# Visit to the website http://www.higherlowergame.com/ and try the game.

#try the final project before starting code..(play many time to understand the logic)
# https://replit.com/@appbrewery/higher-lower-final?v=1

# Try To Write Code on 02_Solution_01.Py by making logic of this game, dont copy/paste from anywhere, try to yourself firstly. in the end you can see the final solution at the 03_Project_Solution.Py 

# USE art.py and game_data.Py in your code...