# Debug Odd or Even Exercise...

# Instruction 
    # 1. Read the Below Code.
    # 2. Spot the problem.
    # 3. Modify the code to fix the problem.


############# CODE to DEBUG #############

number = int(input("which number do you want to check?"))

if number % 2 = 0:
    print("This is an even numberr...")
else:
    print("This is an odd numberr...")























############# DEBUGGED CODE #############

# number = int(input("which number do you want to check?"))

# if number % 2 == 0:
#     print("This is an even numberr...")
# else:
#     print("This is an odd numberr...")