# TITLE : USING THE FOR LOOP WITH PYTHON LIST
# NOTE : Run all three code one by one

fruits = ["Apple", "Banana", "Guava", "Peach"]

# 1)

for fruits in fruits:
    print(fruits)
    

# 2)
    
# for fruits in fruits:
#     print(fruits)
#     print(fruits + " Pie")
    
    

# 3) 

# for fruits in fruits:
#     print(fruits)
#     print(fruits + " Pie")
#     print(fruits)
    
    
    

# 4) 

# for fruits in fruits:
#     print(fruits)
#     print(fruits + " Pie")
# print(fruits)